TEXT = {
    "splash_sub":      "S K N E R U S",
    "splash_prompt":   "[ PRESS SPACE TO PLAY ]",
    "hud_hp":          "HP",
    "hud_kills":       "KILLS",
    "hud_fps":         "FPS",
    "hud_level":       "LVL",
    "hud_controls":    " W/S=MOVE  A/D=STRAFE  Q/E=TURN  UP/DN=180  SPACE=SHOOT  R=RELOAD  ESC=QUIT",
    "msg_kill":        "  ENEMY DESTROYED  ",
    "msg_hit":         "  HIT!  ",
    "warn_close":      "!!! ENEMY IS CLOSE !!!",
    "warn_reload":     ">>> RELOAD NOW <<<",
    "warn_no_ammo":    "!!! NO AMMO LEFT !!!",
    "level_title":     "=== LEVEL COMPLETED ===",
    "level_subtitle":  "GET READY FOR THE NEXT WAVE",
    "level_prompt":    "[ SPACE --> NEXT LEVEL   ESC --> QUIT ]",
    "win_title":       "===  YOU WIN  ===",
    "win_subtitle":    "ALL ROBOTS DESTROYED",
    "win_prompt":      "[ SPACE = PLAY AGAIN   ESC = QUIT ]",
    "dead_title":      "=== YOU DIED ===",
    "dead_subtitle":   "YOU LOST",
    "dead_prompt":     "[ SPACE --> TRY AGAIN   ESC --> QUIT ]",
}
