TEXT = {
    "splash_sub":      "S K N e R U S",
    "splash_prompt":   "[ PRESS SPACE TO PLAY ]",
    "hud_hp":          "HP",
    "hud_kills":       "KILLS",
    "hud_fps":         "FPS",
    "hud_level":       "LVL",
    "hud_controls":    " W/S=MOVE  A/D=STRAFE  Q/E=TURN  UP/DN=180  SPACE=SHOOT  R=RELOAD  Z=SAVE  ESC=MENU",
    "msg_kill":        "  DROM DESTROYED  ",
    "msg_boss_kill":   "  *** BOSS DROM DESTROYED! ***  ",
    "msg_hit":         "  HIT!  ",
    "warn_close":      "!!! DROM IS CLOSE !!!",
    "warn_reload":     ">>> RELOAD NOW <<<",
    "warn_no_ammo":    "!!! NO AMMO LEFT !!!",
    "level_title":     "=== LEVEL COMPLETED ===",
    "level_subtitle":  "GET READY FOR THE NEXT DROMS",
    "level_prompt":    "[ SPACE --> NEXT LEVEL   ESC --> MENU ]",
    "win_title":       "-->  YOU WIN  <--",
    "win_subtitle":    "ALL DROMS DESTROYED",
    "win_prompt":      "[ SPACE --> PLAY AGAIN   ESC --> MENU ]",
    "dead_title":      "--> YOU DIED <--",
    "dead_subtitle":   "THE DROMS GOT YOU",
    "dead_prompt":     "[ SPACE --> TRY AGAIN   ESC --> MENU ]",
}
#@sknrus